### ISSUE TITLE
Unable to select any mods

### ISSUE THREAD

**Issue by CatRyBouReal** [KTibow/Mart#10]
When after reaching step 3, no mods or resource packs show up.
![2023-11-25-125538_1920x1080_scrot](https://github.com/KTibow/Mart/assets/134209879/fff7b89a-2fe7-490b-9e4d-73549c9def1b)

In the console, I can see this error:
`Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'mod.file')` from 'skyclientStuff.js:72'.

**Comment by Hex-4** [comment]
Same error here. The "Add Default Mods" button works fine, and the installed mods show up ingame.

**Comment by KTibow** [comment]
Issue should be fixed now, a bundle was referring to a mod that got renamed by @Wyvest, making the bundle refer to an undefined mod
