### ISSUE TITLE
Libraries needed not listed, add dependancies list that may not be installed

### ISSUE THREAD

**Issue by 100Create** [KTibow/Mart#15]
/Mart-linux_x64: error while loading shared libraries: libwebkit2gtk-4.0.so.37:
Add a requirements.txt or a note on the github

**Comment by 100Create** [comment]
Also its hard to find and install so please add a link

**Comment by KTibow** [comment]
> requirements.txt

What? This isn't a Python-based app, and this library isn't a python library.

> error while loading shared libraries: libwebkit2gtk-4.0.so.37:

Neutralino requires this, it's out of my control, and it's easy enough to deduct "hmm it needs to load libwebkit2gtk? i shall run `apt install libwebkit2gtk`.

**Comment by 100Create** [comment]
> it's easy enough to deduct "hmm it needs to load libwebkit2gtk? i shall run `apt install libwebkit2gtk`.

**_Unable to locate package libwebkit2gtk_**
Also just requirements in the .readme would be fine

**Comment by KTibow** [comment]
Ah, sorry, I meant to say `apt install libwebkit2gtk-4.0`.

**Comment by 100Create** [comment]
**Unable to locate package libwebkit2gtk-4.0
Couldn't find any package by glob 'libwebkit2gtk-4.0'**
Stop being snarky already

**Comment by 100Create** [comment]
Its a hard to find and install package so just tell us on the .readme where to find/build the library

**Comment by KTibow** [comment]
Ah. Looks like it was actually removed due to other factors, yet the docs remain, which is why I mistakenly recommended it.

I've tried to provide exact instructions, but from my research all the ways to get the package working on Ubuntu/similar are pretty complicated. If you find a way that works, let me know and I'll add it into the latest release notes.

I can't tell you "what I did to make it work" because I've never ran into this issue on the versions of Fedora I run. I hope you can understand where I'm coming from.

**Comment by 100Create** [comment]
Ok, sorry, I'll keep looking and add a comment here if I find it

**Comment by 100Create** [comment]
Got the source, going to try build it

**Comment by 100Create** [comment]
The issue may be the installer calls an out of date version because I have libwebkit2gtk-4.1-0 in /usr/share/doc/

**Comment by 100Create** [comment]
OK so, I ran the scripts listed here: https://stackoverflow.com/questions/62301866/how-to-install-the-libwebkitgtk-package-on-ubuntu-20-04-lts and replaced the 1.0.0 with 4.0 and it half works but looks super janky and throws this error in the console:

> SyntaxError: Unexpected identifier 'susStorage'. Expected ';' after variable declaration.

**Comment by 100Create** [comment]
![image](https://github.com/SkyblockClient/Mart/assets/112969644/262e951b-3b07-4d2d-99f8-f472de7e9c58)

**Comment by KTibow** [comment]
That is odd. If I had to guess, the JS runtime used is too old to run some of the things Mart uses.

For now, if you really want to use Mart, I'd recommend installing Chromium and going to https://mart.skyclient.co/.

**Comment by 100Create** [comment]
Solution found and got it to work on Ubuntu LTS, sudo apt-get -y install libwebkit2gtk-4.0-37, I don't know what was up with it earlier (add this to the linux requirements!!!)

**Comment by 100Create** [comment]
However, the mods just don't download in the Skyblock section so idk Ubuntu just doesn't like this
