### ISSUE TITLE
Add check for missing resources file

### ISSUE THREAD

**Issue by RuinTD** [KTibow/Mart#9]
Based on a recent ticket in the SkyClient Discord, it might be a good idea to add a check for the `resource.neu` before instantiating WebView, in case the user tried to run Mart from within the ZIP without extracting... despite the warning from Windows.
![](https://github.com/KTibow/Mart/assets/1149870/a88d319c-0c75-4b73-9056-ba4c094801d1)

**Comment by KTibow** [comment]
That's not possible as the Neutralino binaries are out of my control
